### ISSUE TITLE
Some example if is it possible to use .so libraries from source code which uses JVM FPC target and this project

### ISSUE THREAD

**Issue by JanuszChmiel** [zeljkoc/pandroid#3]
My question is as follows.
Is it possible to use functions and procedures from .so library from The source code, which will be using this project?
I AM very sad, that for example, Cthreads Android unit, Unix unit have not been ported for JVM target. It is for ARM, I386 and other platform.
Since some specific libraries such as bass.so depend on threads communication.
I Am even able to compile included unit for bass.so. But only The version, which is The part of The following project.

https://github.com/r1me/LAMWBassStreamPlayback
Sure, I AM getting one error. I have solved it by removing The line, which have caused The error, but it will have very probably negative effect on whole unit.
How complex would be to create functioning Unit, which would support bass.so also when JVM target of FPC compiler have been used?
Since there are some internal FPC limitations, some commands and directives can not be used.
Thank you very much for yours support.

**Comment by zeljkoc** [comment]
pandroid work thread  
 JLThread = class;

**Comment by JanuszChmiel** [comment]
So it would be possible to call functions and procedures from .so 
libraries? It is excellent.
I have decided to combine The best units from
javavcl
And from yours big project. Because javavcl allow Me to use very simple 
GUI creation approach. I can safely ignore The number positions of 
objects on The screen. I can specify The individual GUI elements 
alligment, left, top, bottom, right. And really, no numbers are necessary.
I will try to add some of yours units, sure not all, since I will 
compile non sense big module.
I have also next plea to you.
How complex would be to construct little function or procedure, which 
will give 1 value if incoming phone call occur. And 0 value, when 
incoming phone call have not occurred.
The important question is, where to add such conditions, if I will use 
bass.so library, bass pascal unit. If I have to add this condition block 
directly to The Bass.pas unit in The place, where play code occurs?

**Comment by zeljkoc** [comment]
Exampl:
https://github.com/zeljkoc/pandroid/tree/master/example/DemoPModule
create: https://github.com/zeljkoc/pandroid/tree/master/example/DemoPModule/pascalsrc/lib/armeabi
libpandroidmodule.so

and read library

**Comment by zeljkoc** [comment]
example incoming call java
http://www.theappguruz.com/blog/detecting-incoming-phone-calls-in-android
