### ISSUE TITLE
please add REQUEST_IGNORE_BATTERY_OPTIMIZATIONS to some of yours libraryes

### ISSUE THREAD

**Issue by JanuszChmiel** [zeljkoc/pandroid#4]
Dear MR Cvijanović,
Unfortunately, starting from Android 6.0 and higher, apps which work on background are very restricted by Android operating system. The onlyone reliable way how to make those background apps to work in background is to include 
REQUEST_IGNORE_BATTERY_OPTIMIZATION
Android permission to Androidmanifest.xml. Unfortunately, simply adding this line to androidmanifest.xml file is not enough.
It is necessary to add some Java code or some mix of Pascal or Java code, which will display Android Sysui dialog window. User must confirm if user wants to add The app to The battery optimisation ingore list.

Please, would somebody of us here add The procedure to some of existing of toThe new Units, which will be The part of Pandroid bundle?

Because my Java language knowledge is very week, I would spent many many hours while adding some code but it will not work.
When user confirm this permission, it is possible to turn The device screen off and running app will work even when screen will be turned off and even when power source will not be active.

Thank you very much for adding this feature to Pandroid bundle.

**Comment by JanuszChmiel** [comment]
Here is important linke to article, which professionally explain whole problematic related to power management.

https://developer.android.com/training/monitoring-device-state/doze-standby

**Comment by JanuszChmiel** [comment]
And here is Java code example which can ask user to add specific application in to white list.

PowerManager pm = (PowerManager) getSystemService(Context.POWER_SERVICE); if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) { if (!pm.isIgnoringBatteryOptimizations(getPackageName())) {     //  Prompt the user to disable battery optimization     Intent intent = new Intent();     intent.setAction(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS);     startActivity(intent);   } }


The problem is, if it would be possible to adapt this code to The Pascal.
Original article with The code was here.

https://developer.zebra.com/blog/keeping-your-android-application-running-when-device-wants-sleep-updated-android-pie

**Comment by zeljkoc** [comment]
Work
android-27
(android 8 or high)


Var
  pm: AOPowerManager;
  intent: ACIntent; 
begin
   pm:= AOPowerManager(getSystemService(ACContext.POWER_SERVICE)) ;
   if (AOBuild.InnerVERSION.fSDK_INT >= AOBuild.InnerVERSION_CODES.M) then begin
       if (not pm.isIgnoringBatteryOptimizations(getPackageName()))  then begin
            // Prompt the user to disable battery optimization
            intent := ACIntent.create;
            intent.setAction(APSettings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS);
            startActivity(intent);
       end;
   end;
end;

**Comment by JanuszChmiel** [comment]
aYes, I Am confirming, that this code recall this dialog.
But I must find other Java code. It can recall much more simpler dialog,
where user only press The button confirm. I Am using older Androide APi
headers, Android API25, bewcause 27 version causes error related to overide
on he Internet radio code.
