### ISSUE TITLE
New repositories  PandroidPackage for Lazarus

### ISSUE THREAD

**Issue by zeljkoc** [zeljkoc/pandroid#5]
add new repositories PandroidPackage for Lazarus

**Comment by JanuszChmiel** [comment]
Oh, and where can I download data from this new repository?

**Comment by zeljkoc** [comment]
https://github.com/zeljkoc/PandroidPackage

uto, 5. svi 2020. u 21:16 JanuszChmiel <notifications@github.com> napisao
je:
